# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qFOjVhnMUnnwj6jOajVnTjNwzvjlrJ8Y
"""



from googletrans import Translator, LANGUAGES
import ipywidgets as widgets
from IPython.display import display

# Initialize translator
translator = Translator()

# Create UI Elements
text_input = widgets.Textarea(placeholder='Type something...', description='Input:', layout={'width': '400px'})
lang_dropdown = widgets.Dropdown(options=[(name.capitalize(), code) for code, name in LANGUAGES.items()], value='es', description='To:')
output_area = widgets.Output()
btn = widgets.Button(description="Translate", button_style='success')

def on_click(b):
    with output_area:
        output_area.clear_output()
        if text_input.value:
            res = translator.translate(text_input.value, dest=lang_dropdown.value)
            print(f"Original ({res.src}): {res.origin}")
            print(f"Translated: {res.text}")

btn.on_click(on_click)
display(text_input, lang_dropdown, btn, output_area)
